#!/bin/bash
domain_name="$1"
domain_task="$2"

if [ "$domain_task" = "prepare" ]; then
	pages=$(cat /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages)
	if [ $pages -ge 12288 ]; then
		domain_name="no_boot"
	fi
	case "$domain_name" in
		"Hikari")
			pages_needed=8192
			echo 3 > /proc/sys/vm/drop_caches
			echo 1 > /proc/sys/vm/compact_memory
			echo $(($pages+$pages_needed)) > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
		;;
		"Rose")
			pages_needed=4096
			echo 3 > /proc/sys/vm/drop_caches
			echo 1 > /proc/sys/vm/compact_memory
			echo $(($pages+$pages_needed)) > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
		;;
		"Rika")
			pages_needed=2048
			echo 3 > /proc/sys/vm/drop_caches
			echo 1 > /proc/sys/vm/compact_memory
			echo $(($pages+$pages_needed)) > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
	esac
fi

if [ "$domain_task" = "release" ]; then
	pages=$(cat /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages)
	if [ $pages -le 0 ]; then
		domain_name="no_boot"
	fi
	case "$domain_name" in
		"Hikari")
			pages_needed=8192
			echo $(($pages-$pages_needed)) > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
		;;
		"Rose")
			pages_needed=4096
			echo $(($pages-$pages_needed)) > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
		;;
		"Rika")
			pages_needed=2048
			echo $(($pages-$pages_needed)) > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
		;;
	esac
fi
